# This is a demo using two subsets of `sample_data` from the AutoScore package.
# The outcome used in this demo is inpatient mortality (binary).

library(AutoScore)
library(tidyverse)
library(ggplot2)
library(mle.tools)
library(rjson)
library(rstudioapi)

setwd(dirname(getSourceEditorContext()$path))
source("../../code/R/fedscore_binary.R")
source("../../code/R/helpers_binary.R")
# source("../../code/R/dclr.R")

##### Import data
# Read data for two sites (split into train, validation and test sets)
dat1_split <- readRDS("../../data/binary/site1_hete.rds")
dat2_split <- readRDS("../../data/binary/site2_hete.rds")

##### Module 1: Obtain federated ranking
# each site first obtain and write ranks independently:
rank.s1 <- AutoScore::AutoScore_rank(dat1_split$train)
write_rank(rank.s1, "../../output/binary/ranks/rank1.csv")
rank.s2 <- AutoScore::AutoScore_rank(dat2_split$train)
write_rank(rank.s2, "../../output/binary/ranks/rank2.csv")
# then get global rank:
rank.fed <- AutoScore_Frank(K = 2, path = "../../output/binary/ranks/") # by using results generated by RF at each site

# take a look at the rank:
rank.fed[,c("var", "rank1", "rank2", "rank_fed")]

# get the variable list in the order of federated ranking:
var.rank <- rank.fed$var[1:9]


##### Module 2: Obtain unified cutoff vectors
# each site independently write cut off into cutoff.json
write_cutoff(df = dat1_split$train, sitename = "hete_S1", path = "../../output/binary/cutoff.json")
write_cutoff(df = dat2_split$train, sitename = "hete_S2", path = "../../output/binary/cutoff.json")
# decide uniform cutoff:
uni_cut <- get_uni_cut(c("hete_S1", "hete_S2"), path = "../../output/binary/cutoff.json")
uni_cut

# Run dCLR algorithm on numerical vec
run_dCLR(dat1_split$train_set, dat2_split$train_set, uni_cut, var.rank[1:5])
# Run dCLR algorithm on cut vec
dat1_train_cat <- transform_df_fixed(dat1_split$train_set, uni_cut)
dat2_train_cat <- transform_df_fixed(dat2_split$train_set, uni_cut)
run_dCLR_cat(dat1_train_cat, dat2_train_cat, uni_cut, var.rank[1:5])
